application: dopemurph
version: collablist
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: main.app

